# Dimensions
WIDTH = 800
HEIGHT = WIDTH * 500 // 800

# Font
FONT_FAMILY = "Arial"
FONT_SIZE_MAIN = 16
FONT_SIZE_PANEL_TITLE = FONT_SIZE_MAIN + 3
FONT_SIZE_TIMER = FONT_SIZE_MAIN + 20
FONT_SIZE_BUTTONS = FONT_SIZE_MAIN - 2
FONT_SIZE_TOTAL_TIME = FONT_SIZE_MAIN + 10
FONT_SIZE_POMODORO_CHOOSING_MINUTES = FONT_SIZE_MAIN + 5
FONT_SIZE_POMODORO_SESSION_TITLE = FONT_SIZE_MAIN + 10
FONT_SIZE_POMODORO_SESSION_TIMER = FONT_SIZE_MAIN + 60
FONT_SIZE_CALENDAR = FONT_SIZE_MAIN - 5
FONT_SIZE_TODO = FONT_SIZE_MAIN - 3

# Colors
BLACK = "#020317"
DARK_BLUE = "#020F43"
VIOLET = "#6345FB"
WHITE = "#CFEBFF"
OTHER_BLUES = {
    "dark": "#032680",
    "middle": "#1942AC",
    "light": "#1D6FFF",
}
PINKS = {
    "light": "#FF7BE1",
    "dark": "#FE3EF2",
}
